ALQUILER_SELECT_ALL=SELECT * FROM Alquiler;
count-solapes=SELECT COUNT(*) FROM Alquiler WHERE matricula = ? AND fecha_inicio < ? AND fecha_fin > ?;
insert=INSERT INTO Alquiler (fecha_inicio, fecha_fin, plazas_reservadas, matricula, dni_socio) VALUES (?,?,?,?,?);

