# =========================================
# Consultas SQL para la tabla Inscripción
# =========================================

# Listar todas las inscripciones
select-findAllInscripciones=SELECT `id_inscripcion`, `tipo`, `fecha_creacion`, `cuota`, `dni_socio` FROM `Inscripcion`;

# Buscar inscripción por ID
select-findInscripcionById=SELECT `id_inscripcion`, `tipo`, `fecha_creacion`, `cuota`, `dni_socio` FROM `Inscripcion` WHERE `id_inscripcion`=?;

# Insertar inscripción (si no pasas fecha, la pone el DEFAULT de la tabla)
insert-addInscripcion= INSERT INTO Inscripcion (tipo, fecha_creacion) VALUES (?, ?);

# Actualizar tipo y cuota
update-updateInscripcion=UPDATE Inscripcion SET tipo = ?, dni_socio = ?, fecha_creacion = ? WHERE id_inscripcion = ?;

# Eliminar inscripción
delete-deleteInscripcionById=DELETE FROM `Inscripcion` WHERE `id_inscripcion`=?;

# Listar inscripciones (id, dni titular, num familiares, cuota actual)
select-listarInscripciones=SELECT i.`id_inscripcion` AS id_inscripcion, (SELECT s.`dni_socio` FROM `Socio` s WHERE s.`id_inscripcion` = i.`id_inscripcion` AND s.`rol`='Titular' LIMIT 1) AS dni_titular, SUM(CASE WHEN s.`rol`='Titular' THEN 0 ELSE 1 END) AS num_familiares, i.`cuota` AS cuota FROM `Inscripcion` i LEFT JOIN `Socio` s ON s.`id_inscripcion` = i.`id_inscripcion` GROUP BY i.`id_inscripcion`, dni_titular, i.`cuota` ORDER BY i.`id_inscripcion`;

#Actualizar Cuota 
update-updateCuota=UPDATE Inscripcion SET cuota = ? WHERE id_inscripcion = ?;

update-cuotaDni=UPDATE Inscripcion SET cuota = ?, dni_socio = ? WHERE id_inscripcion = ?;