# =========================================
# Consultas SQL para la tabla Patron
# =========================================

# Listar todos los patrones
select-findAllPatrones=SELECT dni_patron, nombre, apellidos, fecha_nacimiento, fecha_exp_patron FROM Patron;

# Buscar patrón por DNI
select-findPatronByDni=SELECT dni_patron, nombre, apellidos, fecha_nacimiento, fecha_exp_patron FROM Patron WHERE dni_patron = ?;

# Insertar un nuevo patrón
insert-addPatron=INSERT INTO Patron (dni_patron, nombre, apellidos, fecha_nacimiento, fecha_exp_patron) VALUES (?, ?, ?, ?, ?);

# Modificar patrón
update-updatePatron=UPDATE Patron SET nombre=?, apellidos=?, fecha_nacimiento=?, fecha_exp_patron=? WHERE dni_patron=?;

# Eliminar patrón
delete-deletePatronByDni=DELETE FROM Patron WHERE dni_patron = ?;

# Buscar patrón por fecha de expiración
select-findByExpiracion=SELECT * FROM Patron WHERE fecha_exp_patron <= ?;

# Patrones libres (no asignados a ninguna embarcación)
select-findPatronesLibres=SELECT p.dni_patron, p.nombre, p.apellidos, p.fecha_nacimiento, p.fecha_exp_patron \
FROM Patron p \
WHERE p.dni_patron NOT IN (SELECT dni_patron FROM Embarcacion WHERE dni_patron IS NOT NULL);
