# =========================================
# Consultas SQL para la tabla Reserva
# =========================================

# Listar todas las reservas
select-all=SELECT id_reserva, fecha, plazas_reservadas, descripcion, precio_total, dni_socio, matricula FROM Reserva;

# Insertar una nueva reserva
insert=INSERT INTO Reserva (fecha, plazas_reservadas, descripcion, precio_total, dni_socio, matricula) VALUES (?,?,?,?,?,?);

# Contar reservas de una embarcación en una fecha concreta
count-by-boat-and-date=SELECT COUNT(*) FROM Reserva WHERE matricula = ? AND DATE(fecha) = ?;