ALQUILER_SELECT_ALL=SELECT * FROM Alquiler;
count-solapes=SELECT COUNT(*) FROM Alquiler WHERE matricula = ? AND fecha_inicio < ? AND fecha_fin > ?;
insert=INSERT INTO Alquiler (fecha_inicio, fecha_fin, plazas_reservadas, matricula, dni_socio) VALUES (?,?,?,?,?);

# Buscar alquiler por ID
select-findById=SELECT id_alquiler, fecha_inicio, fecha_fin, plazas_reservadas, matricula, dni_socio, precio_total FROM Alquiler WHERE id_alquiler = ?;

# Actualizar plazas reservadas y precio total
update-alquiler=UPDATE Alquiler SET plazas_reservadas = ?, precio_total = ? WHERE id_alquiler = ?;

# Eliminar alquiler
delete-alquiler=DELETE FROM Alquiler WHERE id_alquiler = ?;