# =========================================
# Consultas SQL para la tabla Embarcacion
# =========================================

# Listar todas las embarcaciones
select-findAllEmbarcaciones=SELECT matricula, tipo, nombre, numero_plazas, dimensiones, dni_patron FROM Embarcacion;

# Buscar embarcación por matrícula
select-findEmbarcacionByMatricula=SELECT matricula, tipo, nombre, numero_plazas, dimensiones, dni_patron FROM Embarcacion WHERE matricula = ?;

# Insertar una nueva embarcación
insert-addEmbarcacion=INSERT INTO Embarcacion (matricula, tipo, nombre, numero_plazas, dimensiones, dni_patron) VALUES (?, ?, ?, ?, ?, ?);

# Modificar embarcación
update-updateEmbarcacion=UPDATE Embarcacion SET tipo=?, nombre=?, numero_plazas=?, dimensiones=?, dni_patron=? WHERE matricula=?;

# Eliminar embarcación
delete-deleteEmbarcacionByMatricula=DELETE FROM Embarcacion WHERE matricula = ?;

# Borrar todas las embarcaciones
delete-deleteAllEmbarcaciones=DELETE FROM Embarcacion;

# Buscar embarcaciones por DNI del patrón
select-findEmbarcacionesByDniPatron=SELECT matricula, tipo, nombre, numero_plazas, dimensiones, dni_patron FROM Embarcacion WHERE dni_patron = ?;

# Buscar embarcaciones por tipo
select-findEmbarcacionesByTipo=SELECT matricula, tipo, nombre, numero_plazas, dimensiones, dni_patron FROM Embarcacion WHERE tipo = ?;

