# =========================================
# Consultas SQL para la tabla socios
# =========================================

# Listar todos los socios
select-findAllSocios=SELECT dni_socio, nombre, apellidos, fecha_nacimiento, direccion, fecha_inscripcion, es_patron, id_inscripcion, rol FROM Socio;

# Buscar socio por DNI
select-findSocioByDni=SELECT dni_socio, nombre, apellidos, fecha_nacimiento, direccion, fecha_inscripcion, es_patron, id_inscripcion, rol  FROM Socio WHERE dni_socio = ?;

# Insertar un nuevo socio
insert-addSocio=INSERT INTO Socio (dni_socio, nombre, apellidos, fecha_nacimiento, direccion, fecha_inscripcion, es_patron, id_inscripcion, rol) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);

# Buscar socios que son patrón
select-findSociosPatron=SELECT dni_socio, nombre, apellidos, fecha_nacimiento, direccion, fecha_inscripcion, es_patron, id_inscripcion, rol FROM Socio WHERE es_patron = 1;

#Modificar socio
update-updateSocio=UPDATE Socio SET nombre=?, apellidos=?, fecha_nacimiento=?, direccion=?, fecha_inscripcion=?, es_patron=?, id_inscripcion=?, rol=? WHERE dni_socio=?

#Eliminar Socio
delete-deleteSocioByDni=DELETE FROM Socio WHERE dni_socio = ?

#Buscar Id_Inscripcion 
select-findByInscripcionId=SELECT dni_socio, nombre, apellidos, fecha_nacimiento, direccion, fecha_inscripcion, es_patron, id_inscripcion, rol FROM Socio WHERE id_inscripcion = ?;

#Desvincular Socios Inscripcion
update-desvincularSocio=UPDATE Socio SET id_inscripcion = NULL WHERE id_inscripcion = ?;

#Desvincular socio Titular con inscripción
update-desvincularTitular=UPDATE Inscripcion SET dni_socio = NULL WHERE dni_socio = ?;

